name: jz_vis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy = 2.2.4
  - pandas = 2.2.3
  - scipy = 1.15.2
  - statsmodels = 0.14.4
  - plotly = 6.0.1
  - matplotlib = 3.10.1
  - vispy=0.15.2
  - pyqt=5.15.11